apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.app.name}}-service
  namespace: {{ .Values.namespace.name}}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: {{ .Values.app.name}}
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 32002
